# Project information
site_name: Microservices with Kubernetes (Developer User Guide)
site_url: https://akeesari.github.io/mkdocs/
# Author details
site_author: Anji Keesari
site_description: >-
  Building and Managing Microservices with Kubernetes using Argocd & Helm
  Azure and Azure DevOps Pipelines.

# Page tree
nav:
  - Home:
    - Home: home/index.md      
  - Getting started:
    - Table of Contents: gettingstarted/toc.md      
    - Introduction: gettingstarted/introduction.md    
    - Workstation configuration: gettingstarted/workstation.md
    - Download & Install software: gettingstarted/software.md
  - Microservices:
      - Microservices: microservices/chapter-1.md
      # Chapters:
      - chapter-1: microservices/chapters/chapter-1.1.md
      - chapter-2: microservices/chapters/chapter-1.2.md
  - Azure:
    - Infrastructure: azure/infrastructure.md
  - DevOps:
    - Azure DevOps: devops/devops.md
  - ArgoCD:
    - Argo CD: argocd/argocd.md
  - Helm-Charts:
    - Helm Charts: helmcharts/helm-charts.md
  - Miscellaneous:
      - Index1: miscellaneous/index.md
      - mkdocs-samples: miscellaneous/mkdocs-samples.md
      - Section1:
        - page-1 : miscellaneous/section1/page-1.md
        - page-3 : miscellaneous/section1/page-2.md
        - page-3 : miscellaneous/section1/page-3.md
      - Section2:
        - page-1 : miscellaneous/section2/page-1.md
        - page-3 : miscellaneous/section2/page-2.md
        - page-3 : miscellaneous/section2/page-3.md
      
  - About:
    - About Us: aboutus.md
  - Contact:
    - Contact Us: contact.md

# # Repository details
# repo_name: akeesari.github.io/mkdocs/
# repo_url: https://akeesari.github.io/mkdocs/

# Configuration
theme:
  name: material # readthedocs
  custom_dir: overrides
  # nav_style: dark
  shortcuts:
      help: 191    # ?
      next: 78     # n
      previous: 80 # p
      search: 83   # s
  features:
  - content.code.copy
  - content.code.annotate
  # - content.tabs.link
  # - header.autohide
  # - navigation.expand
  - navigation.indexes
  - navigation.footer
  - content.tooltips
  - navigation.tabs
  # - navigation.tabs.sticky
  # - navigation.sections
  # - navigation.expand
  # - toc.integrate
  - navigation.top
  - navigation.instant
  - navigation.tracking
  - header.autohide
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  
  language: en
  
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  
  extra_css:
  - stylesheets/extra.css

  extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/

plugins:
  - search
  
# hide:
#   - footer

# copyright   
copyright: |
  Copyright &copy; 2023 <a href="akeesari.github.io/mkdocs"  target="_blank" rel="noopener">Anji Keesari</a>