# Copyright (c) 2023 Anji Keesari <anjkeesari@gmail.com>

# Project information
site_name: Microservices with Kubernetes (Developer User Guide)
site_url: https://akeesari.github.io/micros-k8s/
# repo_url: https://github.com/akeesari/microservices-with-k8s
edit_uri: edit/main/docs/

# Author details
site_author: Anji Keesari
site_description: >-
  Build and Deploy Microservices on Kubernetes using ArgoCD & Helm
  Azure and Azure DevOps Pipelines.

# # Repository details
# repo_name: akeesari.github.io/mkdocs/
# repo_url: https://akeesari.github.io/mkdocs/

# Configuration
theme:
  name: material # readthedocs
  custom_dir: overrides
  # nav_style: dark
  shortcuts:
      help: 191    # ?
      next: 78     # n
      previous: 80 # p
      search: 83   # s
  features:
  - content.code.copy
  - content.code.annotate
  # - content.tabs.link
  # - header.autohide
  # - navigation.expand
  - navigation.indexes
  - navigation.footer
  - content.tooltips
  - navigation.tabs
  # - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand
  # - toc.integrate
  - navigation.top
  - navigation.instant
  - navigation.tracking
  - header.autohide
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  
  language: en
  
  # use_directory_urls: true

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  
  extra_css:
      - css/custom.css

  extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - abbr
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - def_list
  - meta
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  # - toc:                 
  #     permalink: true

extra:
  analytics:
    provider: google
    property: G-KR7ZFHXJM1
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/

  footer: |
      <style>
        .md-footer {
          display: none;
        }
      </style>
plugins:
  - search
  # - awesome-pages
     # Adding the pdf-export plugin
  # - pdf-export:
  #     combined: true
hide:
  - footer
# google_analytics: ["UA-118407822-1", "kubernetes.github.io"]


# copyright   
copyright: |
  Copyright &copy; 2023 <a href="akeesari.github.io/mkdocs"  target="_blank" rel="noopener">Anji Keesari</a>


# Page tree
nav:
  - Home:
    - Home: index.md      
  - Getting started:
    - Table of Contents: gettingstarted/toc.md    
    - About the Author: gettingstarted/about-author.md      
    - Acknowledgments: gettingstarted/acknowledgments.md      
    - Introduction: gettingstarted/introduction.md    
    - Lab Format: gettingstarted/lab-format.md    
  - Microservices:
      - Getting started with Microservices : microservices/0.gettingstarted.md
      - Getting Started with Docker & Containerization : microservices/0-docker.md
      - Developing applications inside a Dev Containers : microservices/0-dev-containers.md
      - Create your first microservice with .NET Core : microservices/1.aspnet-api.md
      - Create your second microservice with Node JS : microservices/2.node-api.md      
      # - MicroFrontend Overview : microservices/microfrontend.md
      - Create your first website using .NET Core MVC : microservices/3.aspnet-app.md      
      - Create your second website using React JS : microservices/4.react-app.md      
      # - Create Website-3 : microservices/5.blazor-app.md
      - Create your first database with SQL server : microservices/6.sqlserver-db.md
      - Create your second database with PostgreSQL : microservices/7.postgresql-db.md
  - Azure (IaC):
    - Infrastructure as Code (IaC): azure/1-iac.md
    - Microservices Architecture on AKS: azure/1-microservices-architecture-on-aks.md
    # - Azure Naming & Tagging Conventions: azure/2-naming-conventions.md
    - Azure Account & Subscription Management: azure/3-azure-account-subscription.md
    # - Create new subscription: azure/4-azure-subscription.md
    # - Register resource providers: azure/5-resource-providers.md
    - Setup Terraform Foundation Part-1: azure/6-tf-foundation-1.md
    - Setup Terraform Foundation Part-2: azure/6-tf-foundation-2.md
    - Create Log Analytics Workspace using terraform: azure/7-log-analytics-workspace.md
    -  Create Virtual Network using terraform: azure/8-vnet.md
    -  Create Azure Container Registry (ACR) using terraform: azure/9-acr.md
    -  Create Azure Application Gateway using terraform: azure/10-app-gateway.md
    -  Create Azure Kubernetes Service (AKS) using terraform: azure/11-aks.md    
    -  Create Azure PostgreSQL - Flexible Server using terraform: azure/12-postgresql.md    
    # -  PostgreSQL Database Access Control with Azure AD Groups: azure/12.1-postgresql-access-control.md    
    -  Create Azure Key Vault using Terraform: azure/13-key-vault.md
    -  Create Azure Cache for Redis using Terraform: azure/14-redis-cache.md
    -  Create Storage Account using Terraform: azure/15-storage-account.md
    -  Azure Event Hubs Introduction: azure/16-event-hubs-part-1.md
    -  Create Azure Event Hubs using Terraform: azure/16-event-hubs-part-2.md
    -  Create Front Door and CDN profile using Terraform: azure/17-cdn-frontdoor.md
  - Kubernetes:
    - Getting Started with Docker Container: kubernetes/0.getting-started.md
    - Prepare an application for Azure Kubernetes Service (AKS): kubernetes/1-prepare-app.md
    - Deploying an .NET Core API to Azure Kubernetes Service (AKS): kubernetes/2-deploy-api.md
    - Deploying an ASP.NET Core MVC to Azure Kubernetes Service (AKS): kubernetes/2-deploy-app.md
    - Working with AKS cluster using kubectl : kubernetes/3-working-with-aks.md
    - Setup NGINX ingress controller in AKS using Terraform : kubernetes/4-ingress-controller-nginx.md
    - Setup Application Gateway ingress controller (AGIC) in AKS using Terraform : kubernetes/4.1-ingress-controller-agic.md
    - Setup Cert-Manager in AKS using Terraform : kubernetes/5-cert-manager.md
    - Issue the Let's Encrypt SSL Certificate to the Website : kubernetes/5.1-issue-cert.md
    - Troubleshooting Problems with Let's Encrypt Certificates : kubernetes/5.2-cert-troubleshooting.md
    - Integrating Azure Key Vault with AKS using Terraform : kubernetes/6-aks-kv-integration.md
    # - Create YAML Manifests for Microservice-1 : kubernetes/5.1-manifests-microservice-1.md
    # - Create YAML Manifests for Microservice-2 : kubernetes/5.2-manifests-microservice-2.md    
    - Kubernetes Pod troubleshooting : kubernetes/pod-troubleshooting.md    
    - Create a new user node pool in AKS : kubernetes/aks-create-nodepool.md
    - Upgrade or Resize node pools in AKS : kubernetes/aks-upgrade-nodepool.md
  - Azure DevOps:
    - Azure DevOps Overview : devops/1-devops-overview.md
    - Create your first service connection : devops/pipelines/1-service-connections.md
    - Create Pipeline for .NET Core Web API : devops/pipelines/2-pipeline-aspnet-api.md
    - Create Pipeline for ASP.NET Core MVC Project : devops/pipelines/3-pipeline-aspnet-app.md

  - Argo CD: 
        - Introduction to Argo CD: argocd/1-argocd-intro.md
        - Install Argo CD in Kubernetes: argocd/2-install-argocd.md
        - Install & Interact with ArgoCD CLI: argocd/3-install-argocd-cli.md
        - Registering an AKS Cluster with Argo CD: argocd/register-cluster.md
        - Deploy your first application with Argo CD: argocd/deploy-app.md
        - Create new ArgoCD Project: argocd/argocd-project.md
        - Create new Repository in ArgoCD: argocd/argocd-repo.md
  - Helm Charts:
        - Introduction to Helm Charts: helmchart/1-introduction.md
        - Create your first Helm chart: helmchart/2-create-helm.md
        - Frequently used Helm commands details: helmchart/3-helm-cmds.md
        - Create Helm chart for Microservices: helmchart/4-helm-microservices.md    
  # - Contact:
  #   - Contact: contact.md
