# Project information
site_name: Microservices with Kubernetes (Developer User Guide)
site_url: https://akeesari.github.io/mkdocs/
# Author details
site_author: Anji Keesari
site_description: >-
  Building and Managing Microservices with Kubernetes using Argocd & Helm
  Azure and Azure DevOps Pipelines.

# Page tree
nav:
  - Home:
    - Home: index.md      
  - Getting started:
    - Table of Contents: gettingstarted/toc.md      
    - Introduction: gettingstarted/introduction.md    
    - Developer Workstation Configuration: gettingstarted/workstation.md    
    - Download & Install software:
       - Windows OS: gettingstarted/software/windows.md
       - Mac OS: gettingstarted/software/mac.md
    - Technology Stack: gettingstarted/tech-stack.md
  - Microservices:
      - Getting started with Microservices : microservices/gettingstarted.md
      - Create Micrservice-1 with .NET Core: microservices/aspnet-api.md
      # - Create Micrservice-2 with Node JS: microservices/nodejs-api.md
      # - Create Micrservice-3 with Java: microservices/java-api.md
      # - Create Website-1 with ASP.NET MVC: microservices/aspnet-app.md
      # - Create Website-2 with React JS: microservices/reactjs-app.md
      # - Create Website-3 with Blazor : microservices/blazor-app.md
      # - Create Database-1 with SQL : microservices/sqldb.md
      # - Create Database-2 with PostgreSQL : microservices/psqldb.md
  - Azure (IaC):
    - Infrastructure as Code (IaC): azure/1-iac.md
    - Azure Naming Conventions: azure/2-naming-conventions.md
    - Azure Free Account: azure/3-azure-account.md
    - Create new subscription: azure/4-azure-subscription.md
    - Create Terraform Foundation: azure/5-tf-fundation.md
    
  - DevOps:
    - Azure DevOps: devops/devops.md
  - ArgoCD:
    - Argo CD: argocd/argocd.md
  - Helm-Charts:
    - Helm Charts: helmcharts/helm-charts.md
  # - Miscellaneous:
  #     - Index1: miscellaneous/index.md
  #     - mkdocs-samples: miscellaneous/mkdocs-samples.md
  #     - Section1:
  #       - page-1 : miscellaneous/section1/page-1.md
  #       - page-3 : miscellaneous/section1/page-2.md
  #       - page-3 : miscellaneous/section1/page-3.md
  #     - Section2:
  #       - page-1 : miscellaneous/section2/page-1.md
  #       - page-3 : miscellaneous/section2/page-2.md
  #       - page-3 : miscellaneous/section2/page-3.md
      
  # - About:
  #   - About Us: aboutus.md
  - Contact:
    - Contact Us: contact.md

# # Repository details
# repo_name: akeesari.github.io/mkdocs/
# repo_url: https://akeesari.github.io/mkdocs/

# Configuration
theme:
  name: material # readthedocs
  custom_dir: overrides
  # nav_style: dark
  shortcuts:
      help: 191    # ?
      next: 78     # n
      previous: 80 # p
      search: 83   # s
  features:
  - content.code.copy
  - content.code.annotate
  # - content.tabs.link
  # - header.autohide
  # - navigation.expand
  - navigation.indexes
  - navigation.footer
  - content.tooltips
  - navigation.tabs
  # - navigation.tabs.sticky
  # - navigation.sections
  - navigation.expand
  # - toc.integrate
  - navigation.top
  - navigation.instant
  - navigation.tracking
  - header.autohide
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  
  language: en
  
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  
  extra_css:
  - stylesheets/extra.css

  extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:                 
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/

  footer: |
      <style>
        .md-footer {
          display: none;
        }
      </style>
plugins:
  - search
     # Adding the pdf-export plugin
  # - pdf-export:
  #     combined: true
hide:
  - footer

# copyright   
copyright: |
  Copyright &copy; 2023 <a href="akeesari.github.io/mkdocs"  target="_blank" rel="noopener">Anji Keesari</a>