# Copyright (c) 2023 Anji Keesari <anjkeesari@gmail.com>

# Project information
site_name: Microservices with Kubernetes (Developer User Guide)
site_url: https://akeesari.github.io/micros-k8s/
# repo_url: https://github.com/akeesari/microservices-with-k8s
edit_uri: edit/main/docs/

# Author details
site_author: Anji Keesari
site_description: >-
  Build and Deploy Microservices Applications on Kubernetes platform using Argocd & Helm
  Azure and Azure DevOps Pipelines.

# # Repository details
# repo_name: akeesari.github.io/mkdocs/
# repo_url: https://akeesari.github.io/mkdocs/

# Configuration
theme:
  name: material # readthedocs
  custom_dir: overrides
  # nav_style: dark
  shortcuts:
      help: 191    # ?
      next: 78     # n
      previous: 80 # p
      search: 83   # s
  features:
  - content.code.copy
  - content.code.annotate
  # - content.tabs.link
  # - header.autohide
  # - navigation.expand
  - navigation.indexes
  - navigation.footer
  - content.tooltips
  - navigation.tabs
  # - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand
  # - toc.integrate
  - navigation.top
  - navigation.instant
  - navigation.tracking
  - header.autohide
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  
  language: en
  
  # use_directory_urls: true

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  
  extra_css:
      - css/custom.css

  extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - abbr
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - def_list
  - meta
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  # - toc:                 
  #     permalink: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/

  footer: |
      <style>
        .md-footer {
          display: none;
        }
      </style>
plugins:
  - search
  # - awesome-pages
     # Adding the pdf-export plugin
  # - pdf-export:
  #     combined: true
hide:
  - footer
# google_analytics: ["UA-118407822-1", "kubernetes.github.io"]


# copyright   
copyright: |
  Copyright &copy; 2023 <a href="akeesari.github.io/mkdocs"  target="_blank" rel="noopener">Anji Keesari</a>


# Page tree
nav:
  - Home:
    - Home: index.md      
  - Getting started:
    - Table of Contents: gettingstarted/toc.md    
    - About the Author: gettingstarted/about-author.md      
    - Acknowledgments: gettingstarted/acknowledgments.md      
    - Introduction: gettingstarted/introduction.md    
    - Developer Workstation Configuration: gettingstarted/workstation.md    
    - Download & Install software:
       - Windows OS: gettingstarted/software/windows.md
       - Mac OS: gettingstarted/software/mac.md
    - Technology Stack: gettingstarted/tech-stack.md
  - Microservices:
      - Getting started with Microservices : microservices/1.gettingstarted.md
      - Create Microservice-1 with .NET Core: microservices/2.aspnet-api.md
      # - Create Micrservice-2 with Node JS: microservices/nodejs-api.md
      # - Create Micrservice-3 with Java: microservices/java-api.md
      - MicroFrontend Overview : microservices/microfrontend.md
      - Create MicroFrontend-1 with ASP.NET MVC: microservices/aspnet-app.md      
      - Create MicroFrontend-2 with React JS: microservices/react-app.md      
      # - Create Website-2 with React JS: microservices/reactjs-app.md
      # - Create Website-3 with Blazor : microservices/blazor-app.md
      # - Create Database-1 with SQL : microservices/sqldb.md
      # - Create Database-2 with PostgreSQL : microservices/psqldb.md
  - Azure (IaC):
    - Infrastructure as Code (IaC): azure/1-iac.md
    - Azure Naming & Tagging Conventions: azure/2-naming-conventions.md
    - Create Azure Free Account: azure/3-azure-account.md
    - Create new subscription: azure/4-azure-subscription.md
    - Register resource providers: azure/5-resource-providers.md
    - Create Terraform Foundation Part-1: azure/6-tf-foundation-1.md
    - Create Terraform Foundation Part-2: azure/6-tf-foundation-2.md
    - Create Log Analytics Workspace using terraform: azure/7-log-analytics-workspace.md
    -  Create Virtual Network using terraform: azure/8-vnet.md
    -  Create Azure Container Registry (ACR) using terraform: azure/9-acr.md
    -  Create Azure Kubernetes Service (AKS) using terraform: azure/10-aks.md
  - Kubernetes:
    - Getting Started with Docker Container: kubernetes/0.getting-started.md
    - Prepare an application for Azure Kubernetes Service (AKS): kubernetes/1-prepare-app.md
    - Deploying an application to Azure Kubernetes Service (AKS): kubernetes/2-deploy-app.md
    - Working with AKS cluster using kubectl : kubernetes/3-working-with-aks.md
    - Setup NGINX ingress controller in Kubernetes cluster : kubernetes/4-ingress-controller.md
    - Kubernetes Pod troubleshooting : kubernetes/pod-troubleshooting.md    
  - Azure DevOps:
    - Azure DevOps Overview : devops/1-devops-overview.md
    - Create your first service connection : devops/pipelines/1-service-connections.md
    - Create Pipeline for .NET Core Web API : devops/pipelines/2-pipeline-aspnet-api.md
    - Create Pipeline for ASP.NET Core MVC Project : devops/pipelines/3-pipeline-aspnet-app.md

    - ArgoCD: 
         - ArgoCD Introduction: devops/argocd/argocd-intro.md
         - Install ArgoCD: devops/argocd/install-argocd.md
         - Install ArgoCD CLI: devops/argocd/install-argocd-cli.md
         - Registering an AKS Cluster with Argo CD: devops/argocd/register-cluster.md
         - Deploy your first application with ArgoCD: devops/argocd/deploy-app.md
         - Create new ArgoCD Project: devops/argocd/argocd-project.md
         - Create new Repository in ArgoCD: devops/argocd/argocd-repo.md
    - Helm-Charts:
         - Helm chart Introduction: devops/helmchart/1-introduction.md
         - Create your first Helm chart: devops/helmchart/2-create-helm.md
         - Frequently used Helm commands details: devops/helmchart/3-helm-cmds.md
         - Create Helm chart for Microservices: devops/helmchart/4-helm-microservices.md

  # - ArgoCD:
  #   - Argo CD: argocd/argocd.md
  # - Helm-Charts:
  #   - Helm Charts: helmcharts/helm-charts.md
  - Miscellaneous:
  # - Misc:
      - Kubectl Cheat Sheet: miscellaneous/kubectl-cheat-sheet.md
      - Helm Cheat Sheet: miscellaneous/helm-cheat-sheet.md
      - az acr Cheat Sheet: miscellaneous/az-acr-cheat-sheet.md
      - Git Cheat Sheet: miscellaneous/git-cheat-sheet.md
      - Docker Cheat Sheet: miscellaneous/docker-cheat-sheet.md
      - ArgoCD Cheat Sheet: miscellaneous/argocd-cheat-sheet.md
      # - Section1:
      #   - page-1 : miscellaneous/section1/page-1.md
      #   - page-3 : miscellaneous/section1/page-2.md
      #   - page-3 : miscellaneous/section1/page-3.md
      # - Section2:
      #   - page-1 : miscellaneous/section2/page-1.md
      #   - page-3 : miscellaneous/section2/page-2.md
      #   - page-3 : miscellaneous/section2/page-3.md
      
  - About:
    - About: about.md
  - Contact:
    - Contact: contact.md
