# Project information
site_name: Microservices with Kubernetes (Developer User Guide)
site_url: https://akeesari.github.io/mkdocs/
# Author details
site_author: Anji Keesari
site_description: >-
  Building and Managing Microservices with Kubernetes using Argocd & Helm
  Azure and Azure DevOps Pipelines.

# # Repository details
# repo_name: akeesari.github.io/mkdocs/
# repo_url: https://akeesari.github.io/mkdocs/

# Page tree
nav:
  - Home:
    - Table of Contents: home/toc.md      
    - Introduction: home/introduction.md
  - Microservices:
      Microservices: microservices/chapter-1.md
      Chapters:
        - chapter-1: microservices/chapters/chapter-1.1.md
        - chapter-2: microservices/chapters/chapter-1.2.md
  - Azure:
    - Infrastructure: azure/infrastructure.md
  - DevOps:
    - Azure DevOps: devops/devops.md
  - ArgoCD:
    - Argo CD: argocd/argocd.md
  - Helm-Charts:
    - Helm Charts: helmcharts/helm-charts.md
  - Miscellaneous:
    - Helm Charts: Miscellaneous/helm-charts.md
  - About:
    - About Us: aboutus.md
  - Contact:
    - Contact Us: contact.md
# Configuration
theme:
  name: material # readthedocs
  custom_dir: overrides
  # nav_style: dark
  shortcuts:
      help: 191    # ?
      next: 78     # n
      previous: 80 # p
      search: 83   # s
  features:
  - content.code.annotate
  # - content.tabs.link
  # - header.autohide
  # - navigation.expand
  - navigation.indexes
  - navigation.footer
  - content.tooltips
  - navigation.tabs
  # - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand
  # - toc.integrate
  - navigation.top
  # - navigation.instant
  - navigation.tracking
  - header.autohide
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  
  language: en
  
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  
  markdown_extensions:
    - tables
  # - pymdownx.highlight:
  #     anchor_linenums: true
  # - pymdownx.inlinehilite
  # - pymdownx.snippets
  # - admonition
  # - pymdownx.arithmatex:
  #     generic: true
  # - footnotes
  # - pymdownx.details
  # - pymdownx.superfences
  # - pymdownx.mark
  
  extra_css:
  - stylesheets/extra.css

  extra_javascript:
  - javascripts/extra.js

  # extra:
  #   social:
  #     - icon: fontawesome/brands/github-alt
  #       link: https://github.com/
  #     - icon: fontawesome/brands/twitter
  #       link: https://twitter.com/
  #     - icon: fontawesome/brands/linkedin
  #       link: https://linkedin.com/in/
  #     - icon: fontawesome/brands/instagram
  #       link: https://www.instagram.com/
  
plugins:
  - search
  
# hide:
#   - footer

# copyright   
copyright: |
  Copyright &copy; 2023 <a href="akeesari.github.io/mkdocs"  target="_blank" rel="noopener">Anji Keesari</a>